default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "brendi_manager_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "brendi_manager_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "brendi_manager_production") %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CACHE", "brendi_manager_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_QUEUE", "brendi_manager_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "brendi_manager_production_cable") %>
    migrations_paths: db/cable_migrate
