default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: brendi_manager_development
  # queue:
  #   <<: *default
  #   database: brendi_manager_development_queue

test:
  primary:
    <<: *default
    database: brendi_manager_test
  # queue:
  #   <<: *default
  #   database: brendi_manager_test_queue

production_default: &production_default
  <<: *default
  port: <%= ENV["PROD_DATABASE_PORT"] %>
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>
  host: <%= ENV["PROD_DATABASE_HOST"] %>
  username: <%= ENV["PROD_DATABASE_USERNAME"] %>

production:
  primary:
    <<: *production_default
    database: postgres
  # queue:
  #   <<: *production_default
  #   database: brendi_manager_production_queue